# Generated by Django 5.0.1 on 2025-12-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='8576779956:AAEmqm1yQmtO06aiXdcdUfi-H4ZKqecbZBo', help_text='Токен бота от @BotFather', max_length=200, verbose_name='Токен бота')),
                ('is_active', models.BooleanField(default=True, help_text='Включить/выключить бота', verbose_name='Активен')),
                ('notify_on_quiz', models.BooleanField(default=True, verbose_name='Уведомлять при прохождении анкеты')),
                ('notify_on_booking', models.BooleanField(default=True, verbose_name='Уведомлять при новой записи')),
                ('notify_on_banner_start', models.BooleanField(default=True, verbose_name='Уведомлять при начале отображения баннера')),
                ('notify_on_banner_end', models.BooleanField(default=True, verbose_name='Уведомлять при завершении отображения баннера')),
                ('webhook_url', models.CharField(blank=True, help_text='URL для webhook (заполняется автоматически)', max_length=500, verbose_name='URL webhook')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Настройки Telegram бота',
                'verbose_name_plural': 'Настройки Telegram бота',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(help_text='ID пользователя в Telegram', unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, help_text='Username пользователя в Telegram', max_length=100, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=200, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=200, verbose_name='Фамилия')),
                ('is_admin', models.BooleanField(default=False, help_text='Получает уведомления от бота', verbose_name='Админ')),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли пользователь', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Пользователь Telegram',
                'verbose_name_plural': 'Пользователи Telegram',
                'ordering': ['-created_at'],
            },
        ),
    ]
