# Generated by Django 5.0.1 on 2025-11-28 15:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('question_type', models.CharField(choices=[('single', 'Один ответ'), ('multiple', 'Несколько ответов'), ('text', 'Текстовый ответ')], default='single', max_length=20, verbose_name='Тип вопроса')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Анкета',
                'verbose_name_plural': 'Анкетаы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст ответа')),
                ('points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Баллы')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quizzes.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz', verbose_name='Анкета'),
        ),
        migrations.CreateModel(
            name='ResultRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_points', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимальные баллы')),
                ('max_points', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Максимальные баллы')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок результата')),
                ('description', models.TextField(verbose_name='Описание результата')),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz_results/', verbose_name='Изображение')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_ranges', to='quizzes.quiz', verbose_name='Анкета')),
            ],
            options={
                'verbose_name': 'Диапазон результатов',
                'verbose_name_plural': 'Диапазоны результатов',
                'ordering': ['order', 'min_points'],
            },
        ),
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0, verbose_name='Всего баллов')),
                ('user_name', models.CharField(blank=True, max_length=200, verbose_name='Имя пользователя')),
                ('user_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон пользователя')),
                ('user_email', models.EmailField(blank=True, max_length=254, verbose_name='Email пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='quizzes.quiz', verbose_name='Анкета')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='quizzes.resultrange', verbose_name='Результат')),
            ],
            options={
                'verbose_name': 'Отправка анкетаа',
                'verbose_name_plural': 'Отправки анкетаов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, verbose_name='Текстовый ответ')),
                ('points', models.IntegerField(default=0, verbose_name='Баллы за ответ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.question', verbose_name='Вопрос')),
                ('selected_options', models.ManyToManyField(blank=True, to='quizzes.answeroption', verbose_name='Выбранные варианты')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.quizsubmission', verbose_name='Отправка')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответы на вопросы',
            },
        ),
    ]
