# Generated by Django 5.0.1

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at'], 'verbose_name': 'Анкета', 'verbose_name_plural': 'Анкеты'},
        ),
        migrations.AlterModelOptions(
            name='quizsubmission',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отправка анкеты', 'verbose_name_plural': 'Отправки анкет'},
        ),
    ]

