# Generated by Django 5.0.1 on 2025-11-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright_text', models.CharField(default='© 2024. Все права защищены', max_length=200, verbose_name='Текст копирайта')),
                ('show_contacts', models.BooleanField(default=True, verbose_name='Показывать контакты')),
                ('show_navigation', models.BooleanField(default=True, verbose_name='Показывать навигацию')),
                ('show_social', models.BooleanField(default=False, verbose_name='Показывать соцсети')),
                ('additional_text', models.TextField(blank=True, verbose_name='Дополнительный текст')),
            ],
            options={
                'verbose_name': 'Настройки подвала',
                'verbose_name_plural': 'Настройки подвала',
            },
        ),
        migrations.CreateModel(
            name='HeaderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_text', models.CharField(default='Радуга слов', max_length=100, verbose_name='Текст логотипа')),
                ('logo_url', models.CharField(blank=True, default='/', max_length=200, verbose_name='URL логотипа')),
                ('show_menu', models.BooleanField(default=True, verbose_name='Показывать меню')),
                ('show_phone', models.BooleanField(default=False, verbose_name='Показывать телефон')),
                ('phone_text', models.CharField(blank=True, max_length=50, verbose_name='Текст телефона')),
            ],
            options={
                'verbose_name': 'Настройки шапки',
                'verbose_name_plural': 'Настройки шапки',
            },
        ),
        migrations.CreateModel(
            name='HeroSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('subtitle', models.TextField(verbose_name='Подзаголовок')),
                ('button_text', models.CharField(default='Записаться к логопеду', max_length=100, verbose_name='Текст кнопки')),
                ('button_url', models.CharField(default='#contact-form', max_length=200, verbose_name='URL кнопки')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Фоновое изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Настройки Hero',
                'verbose_name_plural': 'Настройки Hero',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('url', models.CharField(help_text='Например: /services или http://example.com', max_length=200, verbose_name='URL')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_external', models.BooleanField(default=False, help_text='Открывать в новой вкладке', verbose_name='Внешняя ссылка')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Меню',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Политика конфиденциальности', max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Политика конфиденциальности',
                'verbose_name_plural': 'Политика конфиденциальности',
            },
        ),
    ]
