# Generated by Django 5.0.1 on 2025-11-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_footersettings_headersettings_herosettings_menuitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headersettings',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Если загружено, будет использоваться вместо текста', null=True, upload_to='header/', verbose_name='Изображение логотипа'),
        ),
    ]
