# Generated by Django 5.0.1 on 2025-11-28 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_headersettings_logo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='show_booking_button',
            field=models.BooleanField(default=True, help_text='Отображать кнопку записи на карточке и странице услуги', verbose_name='Показывать кнопку "Записаться"'),
        ),
    ]
