# Generated by Django 5.0.1 on 2025-11-28 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_service_booking_form_service_show_booking_button'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#667eea', help_text='Основной цвет сайта (HEX)', max_length=7, verbose_name='Основной цвет')),
                ('gradient_start', models.CharField(default='#667eea', help_text='Цвет начала градиента (HEX)', max_length=7, verbose_name='Начало градиента')),
                ('gradient_end', models.CharField(default='#764ba2', help_text='Цвет конца градиента (HEX)', max_length=7, verbose_name='Конец градиента')),
                ('secondary_color', models.CharField(blank=True, default='#764ba2', help_text='Вторичный цвет для акцентов (HEX)', max_length=7, verbose_name='Вторичный цвет')),
                ('text_color', models.CharField(blank=True, default='#333333', help_text='Основной цвет текста (HEX)', max_length=7, verbose_name='Цвет текста')),
                ('background_color', models.CharField(blank=True, default='#ffffff', help_text='Цвет фона страницы (HEX)', max_length=7, verbose_name='Цвет фона')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Выберите родительский пункт для создания вложенного меню', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.menuitem', verbose_name='Родительский пункт'),
        ),
    ]
