# Generated by Django 5.0.1 on 2025-11-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_sitesettings_menuitem_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headersettings',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Если загружено, будет использоваться вместо текста', null=True, upload_to='logo/', verbose_name='Изображение логотипа'),
        ),
    ]
