# Generated by Django 5.0.1 on 2025-11-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_headersettings_logo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение вместо текста', null=True, upload_to='menu/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='title',
            field=models.CharField(blank=True, help_text='Оставьте пустым, если используете изображение', max_length=100, verbose_name='Название (текст)'),
        ),
    ]
