# Generated by Django 5.0.1 on 2025-11-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_add_image_to_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosettings',
            name='background_color',
            field=models.CharField(default='#FF820E', help_text='Цвет фона (если изображение не загружено или для наложения)', max_length=7, verbose_name='Цвет фона'),
        ),
        migrations.AlterField(
            model_name='herosettings',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Фоновое изображение для Hero секции', null=True, upload_to='hero/', verbose_name='Фоновое изображение'),
        ),
    ]
