# Generated by Django 5.0.1 on 2025-11-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_add_background_color_to_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosettings',
            name='image_position',
            field=models.CharField(choices=[('left', 'Слева'), ('center', 'По центру'), ('right', 'Справа'), ('top', 'Сверху'), ('bottom', 'Снизу'), ('left top', 'Слева сверху'), ('right top', 'Справа сверху'), ('left bottom', 'Слева снизу'), ('right bottom', 'Справа снизу')], default='right', help_text='Расположение изображения на фоне', max_length=20, verbose_name='Позиция изображения'),
        ),
        migrations.AddField(
            model_name='herosettings',
            name='image_size',
            field=models.CharField(choices=[('cover', 'Растянуть (cover)'), ('contain', 'Вместить (contain)'), ('auto', 'Автоматически'), ('100%', '100% размера')], default='cover', help_text='Как изображение должно заполнять область', max_length=20, verbose_name='Размер изображения'),
        ),
        migrations.AddField(
            model_name='herosettings',
            name='overlay_opacity',
            field=models.DecimalField(decimal_places=2, default=0.3, help_text='От 0.00 (прозрачно) до 1.00 (полностью непрозрачно)', max_digits=3, verbose_name='Прозрачность затемнения'),
        ),
        migrations.AddField(
            model_name='herosettings',
            name='show_overlay',
            field=models.BooleanField(default=True, help_text='Темный оверлей для лучшей читаемости текста', verbose_name='Показывать затемнение'),
        ),
    ]
