# Generated by Django 5.0.1 on 2025-11-28 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('content', '0009_add_hero_image_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='booking_form',
            field=models.ForeignKey(blank=True, help_text='Форма, которая откроется при нажатии на кнопку "Записаться"', null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.bookingform', verbose_name='Форма записи'),
        ),
    ]
