# Generated by Django 5.0.1 on 2025-11-28 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_add_booking_form_to_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosettings',
            name='image_scale',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Масштаб изображения в процентах (от 10% до 500%)', max_digits=5, validators=[django.core.validators.MinValueValidator(10.0), django.core.validators.MaxValueValidator(500.0)], verbose_name='Масштаб изображения (%)'),
        ),
    ]
