# Generated by Django 5.0.1 on 2025-11-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_add_image_scale_to_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosettings',
            name='text_align',
            field=models.CharField(choices=[('left', 'По левому краю'), ('center', 'По центру'), ('right', 'По правому краю')], default='left', help_text='Выравнивание заголовка и подзаголовка', max_length=10, verbose_name='Выравнивание текста'),
        ),
    ]
