# Generated by Django 5.0.1 on 2025-11-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_add_text_align_to_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosettings',
            name='image_vertical_align',
            field=models.CharField(choices=[('top', 'Сверху'), ('center', 'По середине'), ('bottom', 'Снизу')], default='center', help_text='Вертикальное расположение изображения (сверху, по середине, снизу)', max_length=20, verbose_name='Вертикальное выравнивание'),
        ),
        migrations.AlterField(
            model_name='herosettings',
            name='image_position',
            field=models.CharField(choices=[('left', 'Слева'), ('center', 'По центру'), ('right', 'Справа')], default='right', help_text='Горизонтальное расположение изображения (слева, по центру, справа)', max_length=20, verbose_name='Горизонтальное выравнивание'),
        ),
    ]
