# Generated by Django 5.0.1 on 2025-11-29 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_bookingform_default_quiz'),
        ('content', '0014_add_header_sizes'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosettings',
            name='button_booking_form',
            field=models.ForeignKey(blank=True, help_text='Выберите форму записи, которая откроется при нажатии (если тип = "Прямая запись")', null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.bookingform', verbose_name='Форма записи для кнопки'),
        ),
        migrations.AddField(
            model_name='herosettings',
            name='button_quiz',
            field=models.ForeignKey(blank=True, help_text='Выберите квиз, который откроется при нажатии (если тип = "Опрос")', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.quiz', verbose_name='Квиз для кнопки'),
        ),
        migrations.AddField(
            model_name='herosettings',
            name='button_type',
            field=models.CharField(choices=[('link', 'Ссылка'), ('quiz', 'Опрос (квиз)'), ('booking', 'Прямая запись')], default='link', help_text='Что произойдет при нажатии на кнопку', max_length=20, verbose_name='Тип кнопки'),
        ),
        migrations.AlterField(
            model_name='herosettings',
            name='button_url',
            field=models.CharField(blank=True, default='#contact-form', help_text='Используется только если тип кнопки = "Ссылка"', max_length=200, verbose_name='URL кнопки'),
        ),
    ]
