# Generated by Django 5.0.1 on 2025-11-29 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_sync_menu_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageblock',
            name='show_title',
            field=models.BooleanField(default=True, help_text='Отображать заголовок блока на странице', verbose_name='Показывать заголовок'),
        ),
        migrations.AddField(
            model_name='homepageblock',
            name='title_align',
            field=models.CharField(choices=[('left', 'Слева'), ('center', 'По центру'), ('right', 'Справа'), ('justify', 'По ширине')], default='center', help_text='Выравнивание заголовка', max_length=10, verbose_name='Выравнивание'),
        ),
        migrations.AddField(
            model_name='homepageblock',
            name='title_bold',
            field=models.BooleanField(default=False, verbose_name='Жирный'),
        ),
        migrations.AddField(
            model_name='homepageblock',
            name='title_color',
            field=models.CharField(default='#333333', help_text='Цвет заголовка в формате HEX (например, #FF820E)', max_length=7, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='homepageblock',
            name='title_custom_css',
            field=models.TextField(blank=True, help_text='Дополнительные CSS стили для заголовка (например: text-decoration: underline; margin-bottom: 20px;)', verbose_name='Дополнительные CSS стили'),
        ),
        migrations.AddField(
            model_name='homepageblock',
            name='title_italic',
            field=models.BooleanField(default=False, verbose_name='Курсив'),
        ),
        migrations.AddField(
            model_name='homepageblock',
            name='title_size',
            field=models.CharField(choices=[('small', 'Маленький'), ('medium', 'Средний'), ('large', 'Большой'), ('xlarge', 'Очень большой')], default='large', help_text='Размер заголовка', max_length=10, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='homepageblock',
            name='title_tag',
            field=models.CharField(choices=[('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h6', 'H6')], default='h2', help_text='HTML тег для заголовка (H1-H6)', max_length=2, verbose_name='Тег заголовка'),
        ),
        migrations.AlterField(
            model_name='homepageblock',
            name='content_page',
            field=models.ForeignKey(help_text='Выберите страницу контента для отображения в этом блоке', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='content.contentpage', verbose_name='Страница для отображения'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='content_page',
            field=models.ForeignKey(blank=True, help_text='Выберите страницу контента, если меню ведет на неё', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='content.contentpage', verbose_name='Страница контента'),
        ),
    ]
