# Generated by Django 5.0.1 on 2025-11-29 14:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_add_title_styling_to_homepage_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Описание страницы с поддержкой форматирования', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Описание'),
        ),
    ]
