# Generated by Django 5.0.1 on 2025-11-29 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_add_ckeditor_to_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosettings',
            name='content_width',
            field=models.CharField(choices=[('narrow', 'Узкая (600px)'), ('medium', 'Средняя (800px)'), ('wide', 'Широкая (1000px)'), ('full', 'На всю ширину (1200px)'), ('custom', 'Произвольная')], default='narrow', help_text='Ширина полезной области для текста в Hero секции', max_length=20, verbose_name='Ширина контента'),
        ),
        migrations.AddField(
            model_name='herosettings',
            name='content_width_custom',
            field=models.IntegerField(blank=True, help_text='Используется только если выбрана "Произвольная" ширина (от 300 до 2000px)', null=True, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(2000)], verbose_name='Произвольная ширина (px)'),
        ),
    ]
