# Generated by Django 5.0.1 on 2025-11-29 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_bookingform_default_quiz'),
        ('content', '0020_add_content_width_to_hero'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogitem',
            name='booking_form_id',
        ),
        migrations.RemoveField(
            model_name='catalogitem',
            name='external_url',
        ),
        migrations.RemoveField(
            model_name='catalogitem',
            name='quiz_slug',
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='button_booking_form',
            field=models.ForeignKey(blank=True, help_text='Выберите форму записи (если тип кнопки - "Запись")', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.bookingform', verbose_name='Форма записи'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='button_quiz',
            field=models.ForeignKey(blank=True, help_text='Выберите квиз (если тип кнопки - "Квиз")', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.quiz', verbose_name='Квиз'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='button_url',
            field=models.CharField(blank=True, help_text='Внешняя ссылка (если тип кнопки - "Внешняя ссылка")', max_length=500, verbose_name='URL кнопки'),
        ),
    ]
