# Generated by Django 5.0.1 on 2025-11-30 16:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_add_welcome_banners'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcomebanner',
            name='blur_background',
            field=models.IntegerField(default=0, help_text='Уровень размытия фона под модальным окном (0-100%). Работает только для типа "Модальное окно"', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Блюр фона под модальным окном'),
        ),
        migrations.AddField(
            model_name='welcomebanner',
            name='display_type',
            field=models.CharField(choices=[('section', 'Раздел сайта'), ('modal', 'Модальное окно')], default='section', help_text='Как будет отображаться баннер: как обычный раздел или модальное окно', max_length=10, verbose_name='Тип отображения'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='button_quiz',
            field=models.ForeignKey(blank=True, help_text='Выберите анкету (если тип кнопки - "Анкета")', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.quiz', verbose_name='Анкета'),
        ),
    ]
