# Generated by Django 5.0.1

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0051_add_image_position_and_target_size_to_catalog_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Настройки цвета сайта', 'verbose_name_plural': 'Настройки цвета сайта'},
        ),
        migrations.RenameIndex(
            model_name='servicebranch',
            new_name='content_ser_service_b84810_idx',
            old_name='content_ser_service_8a1f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='servicebranch',
            new_name='content_ser_is_avai_f2c322_idx',
            old_name='content_ser_is_avail_8b2f3e_idx',
        ),
        migrations.RenameIndex(
            model_name='servicebranchpricehistory',
            new_name='content_ser_service_b1484f_idx',
            old_name='content_ser_service_9c3f4d_idx',
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='image_align',
            field=models.CharField(choices=[('left', 'Слева'), ('right', 'Справа'), ('center', 'По центру')], default='center', help_text='Выравнивание изображения на странице элемента', max_length=10, verbose_name='Выравнивание изображения'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='image_size',
            field=models.CharField(choices=[('small', 'Маленькое'), ('medium', 'Среднее'), ('large', 'Большое'), ('full', 'На всю ширину')], default='medium', help_text='Размер изображения на странице элемента', max_length=10, verbose_name='Размер изображения'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='page',
            field=models.ForeignKey(blank=True, help_text='Страница контента, которая будет использоваться для отображения этого элемента (если включен режим "Может быть открыт как страница")', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_items', to='content.contentpage', verbose_name='Страница контента'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='page',
            field=models.ForeignKey(blank=True, help_text='Страница контента, к которой относится это изображение', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='content.contentpage', verbose_name='Страница контента'),
        ),
        migrations.AlterField(
            model_name='herosettings',
            name='button_quiz',
            field=models.ForeignKey(blank=True, help_text='Выберите анкету, которая откроется при нажатии (если тип = "Опрос")', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.quiz', verbose_name='Анкета для кнопки'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='content_page',
            field=models.ForeignKey(blank=True, help_text='Страница контента, на которую будет вести пункт меню (если выбран тип "Страница")', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='content.contentpage', verbose_name='Страница контента'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение для пункта меню (опционально)', null=True, upload_to='menu/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='title',
            field=models.CharField(help_text='Текст пункта меню', max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, help_text='URL для перехода (если выбран тип "Ссылка"). Можно использовать относительные пути, например: /services/, /about/, или абсолютные: https://example.com', max_length=500, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='URL-адрес'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]

