# Generated by Django 5.0.1

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0052_alter_sitesettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='image_align',
            field=models.CharField(choices=[('left', 'Слева'), ('right', 'Справа'), ('center', 'По центру'), ('full', 'На всю ширину')], default='center', help_text='Как изображение выравнивается относительно текста (используется для карточек в списке)', max_length=10, verbose_name='Выравнивание изображения'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='image_size',
            field=models.CharField(choices=[('small', 'Маленькое (200px)'), ('medium', 'Среднее (400px)'), ('large', 'Большое (600px)'), ('full', 'На всю ширину')], default='medium', help_text='Размер изображения (используется для карточек в списке)', max_length=10, verbose_name='Размер изображения'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='page',
            field=models.ForeignKey(help_text='Каталог можно добавить на страницу любого типа', on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='content.contentpage', verbose_name='Страница'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='page',
            field=models.ForeignKey(help_text='Галерею можно добавить на страницу любого типа', on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='content.contentpage', verbose_name='Страница'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='content_page',
            field=models.ForeignKey(blank=True, help_text='Выберите страницу контента, если меню ведет на неё. Для селектора филиала не используется.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='content.contentpage', verbose_name='Страница контента'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение вместо текста. Для селектора филиала не используется.', null=True, upload_to='menu/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='title',
            field=models.CharField(blank=True, help_text='Оставьте пустым, если используете изображение. Для селектора филиала не используется.', max_length=100, verbose_name='Название (текст)'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, help_text='Заполните, если используете внешнюю ссылку или кастомный URL. Для селектора филиала не используется.', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='order',
            field=models.IntegerField(default=0, help_text='Порядок отображения в списке', verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='slug',
            field=models.SlugField(help_text='Используется в URL страницы (например: privacy, copyright)', max_length=200, unique=True, verbose_name='URL-адрес'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='title',
            field=models.CharField(help_text='Например: Политика конфиденциальности, Защита авторских прав', max_length=200, verbose_name='Заголовок'),
        ),
    ]

