# Generated by Django 5.0.1 on 2025-11-28 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0003_headersettings_logo_image'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название формы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('submit_button_text', models.CharField(default='Записаться', max_length=100, verbose_name='Текст кнопки отправки')),
                ('success_message', models.TextField(default='Спасибо! Мы свяжемся с вами в ближайшее время.', verbose_name='Сообщение об успешной отправке')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Форма записи',
                'verbose_name_plural': 'Формы записи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, help_text='Все данные, отправленные через форму', verbose_name='Данные формы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='booking.bookingform', verbose_name='Форма')),
                ('quiz_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_submissions', to='quizzes.quizsubmission', verbose_name='Отправка анкетаа')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='content.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Отправка формы записи',
                'verbose_name_plural': 'Отправки форм записи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Название поля')),
                ('field_type', models.CharField(choices=[('text', 'Текст'), ('email', 'Email'), ('phone', 'Телефон'), ('textarea', 'Многострочный текст'), ('select', 'Выпадающий список'), ('radio', 'Радиокнопки'), ('checkbox', 'Чекбокс'), ('date', 'Дата'), ('time', 'Время'), ('hidden', 'Скрытое поле')], default='text', max_length=20, verbose_name='Тип поля')),
                ('name', models.CharField(help_text='Используется в HTML, должно быть уникальным в форме', max_length=100, verbose_name='Имя поля (name)')),
                ('placeholder', models.CharField(blank=True, max_length=200, verbose_name='Подсказка')),
                ('help_text', models.CharField(blank=True, max_length=500, verbose_name='Дополнительная подсказка')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательное')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('default_value', models.CharField(blank=True, help_text='Для скрытых полей можно использовать {service_title} для подстановки названия услуги', max_length=500, verbose_name='Значение по умолчанию')),
                ('options', models.TextField(blank=True, help_text='Каждый вариант с новой строки', verbose_name='Варианты выбора (для select/radio)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='booking.bookingform', verbose_name='Форма')),
            ],
            options={
                'verbose_name': 'Поле формы',
                'verbose_name_plural': 'Поля формы',
                'ordering': ['order', 'id'],
                'unique_together': {('form', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FormRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_value', models.CharField(help_text='Если поле имеет это значение, сработает правило', max_length=500, verbose_name='Значение поля')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.formfield', verbose_name='Поле')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='booking.bookingform', verbose_name='Форма')),
                ('quiz', models.ForeignKey(blank=True, help_text='Анкета, который откроется при срабатывании правила', null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz', verbose_name='Анкета/Анкета')),
            ],
            options={
                'verbose_name': 'Правило формы',
                'verbose_name_plural': 'Правила формы',
                'ordering': ['order', 'id'],
            },
        ),
    ]
