# Generated by Django 5.0.1 on 2025-11-28 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingform',
            name='default_quiz',
            field=models.ForeignKey(blank=True, help_text='Квиз, который откроется всегда при отправке формы (без условий). Если указан, будет показан вместо отправки формы.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.quiz', verbose_name='Квиз по умолчанию'),
        ),
    ]
