# Generated by Django 5.0.1 on 2025-12-14 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_add_source_page_to_booking_submission'),
        ('booking', '0003_alter_bookingform_default_quiz_and_more'),
    ]

    operations = [
    ]
