# Generated by Django 5.0.1

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_quiz_options_alter_quizsubmission_options'),
        ('booking', '0004_merge_20251214_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingform',
            name='default_quiz',
            field=models.ForeignKey(blank=True, help_text='Анкета, которая откроется всегда при отправке формы (без условий). Если указана, будет показана вместо отправки формы.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.quiz', verbose_name='Анкета по умолчанию'),
        ),
        migrations.AlterField(
            model_name='bookingsubmission',
            name='quiz_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_submissions', to='quizzes.quizsubmission', verbose_name='Отправка анкеты'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='default_value',
            field=models.CharField(blank=True, help_text='Для скрытых полей можно использовать плейсхолдеры: {service_title} - название услуги, {source_page} - URL страницы источника', max_length=500, verbose_name='Значение по умолчанию'),
        ),
        migrations.AlterField(
            model_name='formrule',
            name='quiz',
            field=models.ForeignKey(blank=True, help_text='Анкета, которая откроется при срабатывании правила', null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz', verbose_name='Анкета'),
        ),
    ]

