# Generated by Django 5.0.1 on 2025-12-03 08:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoyKlassSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(help_text='API ключ из раздела "Настройки - API" в MoyKlass', max_length=200, verbose_name='API ключ')),
                ('access_token', models.CharField(blank=True, help_text='Автоматически обновляется при работе', max_length=500, verbose_name='Токен доступа')),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='Автоматически обновляется', null=True, verbose_name='Токен действителен до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Интеграция активна')),
                ('auto_sync_enabled', models.BooleanField(default=False, help_text='Автоматически синхронизировать данные с MoyKlass', verbose_name='Автоматическая синхронизация')),
                ('sync_interval_minutes', models.IntegerField(default=60, help_text='Как часто синхронизировать данные (минимум 5 минут)', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)], verbose_name='Интервал синхронизации (минуты)')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('sync_students', models.BooleanField(default=True, verbose_name='Синхронизировать учеников')),
                ('sync_payments', models.BooleanField(default=True, verbose_name='Синхронизировать платежи')),
                ('sync_bookings', models.BooleanField(default=True, verbose_name='Синхронизировать записи')),
                ('sync_groups', models.BooleanField(default=False, verbose_name='Синхронизировать группы')),
                ('sync_lessons', models.BooleanField(default=False, verbose_name='Синхронизировать занятия')),
                ('webhook_enabled', models.BooleanField(default=False, help_text='Получать уведомления от MoyKlass о событиях', verbose_name='Включить вебхуки')),
                ('webhook_url', models.URLField(blank=True, help_text='URL для получения вебхуков от MoyKlass', verbose_name='URL для вебхуков')),
                ('log_requests', models.BooleanField(default=True, help_text='Сохранять логи всех запросов к API', verbose_name='Логировать запросы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки MoyKlass',
                'verbose_name_plural': 'Настройки MoyKlass',
            },
        ),
        migrations.CreateModel(
            name='MoyKlassSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('students', 'Ученики'), ('payments', 'Платежи'), ('bookings', 'Записи'), ('groups', 'Группы'), ('lessons', 'Занятия'), ('full', 'Полная синхронизация')], max_length=20, verbose_name='Тип синхронизации')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('error', 'Ошибка'), ('partial', 'Частично')], max_length=10, verbose_name='Статус')),
                ('records_processed', models.IntegerField(default=0, verbose_name='Обработано записей')),
                ('records_created', models.IntegerField(default=0, verbose_name='Создано записей')),
                ('records_updated', models.IntegerField(default=0, verbose_name='Обновлено записей')),
                ('records_errors', models.IntegerField(default=0, verbose_name='Ошибок')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='Длительность (сек)')),
            ],
            options={
                'verbose_name': 'Лог синхронизации',
                'verbose_name_plural': 'Логи синхронизации',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MoyKlassRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], max_length=10, verbose_name='Метод')),
                ('endpoint', models.CharField(max_length=500, verbose_name='Endpoint')),
                ('request_data', models.TextField(blank=True, verbose_name='Данные запроса')),
                ('response_status', models.IntegerField(blank=True, null=True, verbose_name='Статус ответа')),
                ('response_data', models.TextField(blank=True, verbose_name='Данные ответа')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('duration_ms', models.FloatField(blank=True, null=True, verbose_name='Длительность (мс)')),
            ],
            options={
                'verbose_name': 'Лог запроса',
                'verbose_name_plural': 'Логи запросов',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='moyklass_mo_created_8d93d3_idx'), models.Index(fields=['endpoint'], name='moyklass_mo_endpoin_52599a_idx')],
            },
        ),
    ]
