# Generated by Django 5.0.1 on 2025-12-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moyklass', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='moyklassrequestlog',
            name='moyklass_mo_created_8d93d3_idx',
        ),
        migrations.AddIndex(
            model_name='moyklassrequestlog',
            index=models.Index(fields=['created_at'], name='moyklass_mo_created_06ae2f_idx'),
        ),
    ]
