# Generated by Django 5.0.1 on 2025-12-03 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_bookingform_default_quiz'),
        ('moyklass', '0002_remove_moyklassrequestlog_moyklass_mo_created_8d93d3_idx_and_more'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoyKlassIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('booking_form', 'Форма записи'), ('quiz', 'Анкета')], max_length=20, verbose_name='Тип источника')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('booking_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moyklass_integrations', to='booking.bookingform', verbose_name='Форма записи')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moyklass_integrations', to='quizzes.quiz', verbose_name='Анкета')),
            ],
            options={
                'verbose_name': 'Интеграция с MoyKlass',
                'verbose_name_plural': 'Интеграции с MoyKlass',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MoyKlassFieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyklass_field', models.CharField(choices=[('name', 'Имя'), ('phone', 'Телефон'), ('email', 'Email'), ('comment', 'Комментарий'), ('birthday', 'Дата рождения'), ('address', 'Адрес'), ('city', 'Город'), ('country', 'Страна'), ('note', 'Заметка')], max_length=50, verbose_name='Поле в MoyKlass')),
                ('source_field_name', models.CharField(help_text='Имя поля (name) из формы записи или ID вопроса из анкеты', max_length=100, verbose_name='Имя поля в источнике')),
                ('source_field_label', models.CharField(blank=True, help_text='Для отображения в админке', max_length=200, verbose_name='Название поля в источнике')),
                ('is_required', models.BooleanField(default=False, help_text='Если поле не заполнено, лид не будет создан', verbose_name='Обязательное')),
                ('default_value', models.CharField(blank=True, help_text='Используется, если поле не заполнено', max_length=500, verbose_name='Значение по умолчанию')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_mappings', to='moyklass.moyklassintegration', verbose_name='Интеграция')),
            ],
            options={
                'verbose_name': 'Маппинг поля',
                'verbose_name_plural': 'Маппинги полей',
                'ordering': ['order', 'id'],
                'unique_together': {('integration', 'moyklass_field')},
            },
        ),
    ]
